In [8]:
import numpy as np

dizi1= np.array ([0 ,1, 2, 3, 4])
print("Dizimiz:\n",dizi1)

dizi2= np.array ([[0,1,2],[3,4,5]])
print("2.Dizimiz:\n",dizi2)

Dizimiz:
 [0 1 2 3 4]
2.Dizimiz:
 [[0 1 2]
 [3 4 5]]


In [9]:
print("dizinin indisi '3' olan elamanı ha budur uşağım: ",dizi1[3])


dizinin indisi '3' olan elamanı ha budur uşağım:  3


In [11]:
print("2.dizinin indisi '(1,1)' olan elamanı ha budur uşağım: ",dizi2[1,1])
print("2.dizinin indisi '(1,2)' olan elamanı ha budur uşağım: ",dizi2[1,2])


2.dizinin indisi '(1,1)' olan elamanı ha budur uşağım:  4
2.dizinin indisi '(1,2)' olan elamanı ha budur uşağım:  5


In [17]:
dizi2[1,2]=10
print(" 2.dizinin indisi '(1,2)'olan elemanı '5' iken '10' yaptım aha da bak.\n", "2.dizimiz:\n",dizi2)

 2.dizinin indisi '(1,2)'olan elemanı '5' iken '10' yaptım aha da bak.
 2.dizimiz:
 [[ 0  1  2]
 [ 3  4 10]]


In [21]:
dizi4= np.array ([[0,1,2,3],[3,4,5,6],[1,2,3,6],[5,6,2,9]])
print("4.dizimiz:\n",dizi4)

4.dizimiz:
 [[0 1 2 3]
 [3 4 5 6]
 [1 2 3 6]
 [5 6 2 9]]


In [30]:
mat_3x3= np.array([[6,3,8],[2,9,0],[7,4,5]])
print("mat_3x3 dizimiz=\n",mat_3x3)
print("----------------")
print(mat_3x3[1:3,0:2])
print("----------------")
print(mat_3x3[:,[0,2]])

mat_3x3 dizimiz=
 [[6 3 8]
 [2 9 0]
 [7 4 5]]
----------------
[[2 9]
 [7 4]]
----------------
[[6 8]
 [2 0]
 [7 5]]


In [32]:
mat_3x3[:,[0,2]]=[[16,18],[12,10],[17,15]]
print(mat_3x3)


[[16  3 18]
 [12  9 10]
 [17  4 15]]


dd

In [33]:
dizi1[4]=100
print("Dizimiz:\n",dizi1)

Dizimiz:
 [  0   1   2   3 100]


In [34]:
dizi1[-1]= 2014
print("Dizimiz:\n",dizi1)

Dizimiz:
 [   0    1    2    3 2014]


In [51]:
print(dizi1[1:4:2])
print(dizi1[3:0:-2])
print(dizi1[4:0:-1]) #4 indisli elemandan geriye doğru teker teker 0 indisli elemana kadar!# 0 indisli dahil değildir 
print(dizi1[:4]) #başlangıçtan 4 indisli elemana kadar! 4 dahil değil.
print(dizi1[:]) #hepsi

[1 3]
[3 1]
[2014    3    2    1]
[0 1 2 3]
[   0    1    2    3 2014]


In [69]:
dizi1[5]=-4
print(dizi1)

IndexError: index 5 is out of bounds for axis 0 with size 5

In [70]:

dizi2=dizi1
print("dizi1:\n",dizi1)
print("dizi2:\n",dizi2)
dizi2[1]=31
#sadece dizi2'nin elemanını değiştirmeme rağmen dizi1  deki elemanda da değişti.  dizi2=dizi1

dizi1:
 [ 0 31  2  3 -4]
dizi2:
 [ 0 31  2  3 -4]


In [73]:
dizi1= np.array([0,1,2,3,4])
print("dizi1:\n", dizi1)
dizi1= np.append(dizi1,[10]) #diziye ekleme yapmamızı sağlayan komut.
print("dizi1:\n",dizi1)

dizi1:
 [0 1 2 3 4]
dizi1:
 [ 0  1  2  3  4 10]


In [ ]:
print("dizi1:\n", dizi1)
dizi5 = np.insert(dizi1,2,[9,8,7]) # dizide belirtiğimiz indisdeki değeri değiştiririz.
print("dizi5: \n",dizi5)

concatenate() ile dizi birleştirme
Python'da "normal" (standard) dizileri + operatörü ile birleştirebiliyorduk. NumPy matrislerinde bu operatör ile gerçek toplama yapabildiğimizden ötürü, yeni bir komuta gerek olmuş, o komut da işte concatenate:

In [78]:
dizi1 = np.array([0,1,2,3,4])
dizi2 = np.array([9,10,15])
dizi3 = np.concatenate((dizi1,dizi2))
print("dizi3: \n",dizi3)

dizi3: 
 [ 0  1  2  3  4  9 10 15]


In [81]:
mat1=np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12]])
print("mat1 matrisim;\n",mat1)

mat1 matrisim;
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [82]:
print(np.delete(mat1,2))

[ 1  2  4  5  6  7  8  9 10 11 12]


In [84]:
print(np.delete(mat1,2,0)) # mat 1'i al ve onun satırlarından 2 indisli satırı sil. 
#burada 0 ise x ekseni(satır) belirtmekte 1 olursa y ekseni(sütun) 2 olursa z eksenidir. bu matris 2 boyutludur.

[[1 2 3 4]
 [5 6 7 8]]


In [86]:
print(np.delete(mat1,[0,2],1)) 

[[ 2  4]
 [ 6  8]
 [10 12]]


In [87]:
print(np.delete(mat1,[0,2],0))

[[5 6 7 8]]
